import { WorkSpot } from "@/types";

export const MOCK_SPOTS: WorkSpot[] = [
  {
    id: "1",
    name: "테라로사 경포점",
    category: "cafe",
    address: "강릉시 경포로 339",
    lat: 37.7956,
    lng: 128.9006,
    wifi: { available: true, speedMbps: 100 },
    power: { level: "충분함" },
    noise: "언급없음",
    openHours: "08:00 - 22:00",
    congestion: "medium",
    tags: ["커피명소", "넓은공간", "뷰맛집"],
    description:
      "국내 스페셜티 커피의 성지. 탁 트인 경포 뷰와 넓은 좌석 배치로 장시간 작업에 적합합니다. 주말에는 혼잡할 수 있으나 평일 오전은 쾌적합니다.",
    imageUrl: "https://placehold.co/1200x480/e2e8f0/94a3b8?text=테라로사+경포점",
  },
  {
    id: "2",
    name: "강릉 코워킹스페이스",
    category: "coworking",
    address: "강릉시 임영로 152",
    lat: 37.7519,
    lng: 128.8759,
    wifi: { available: true, speedMbps: 500 },
    power: { level: "충분함" },
    noise: "언급됨-조용함",
    openHours: "09:00 - 21:00",
    congestion: "low",
    tags: ["회의실", "1인실", "프린터"],
    description:
      "전용 코워킹 공간으로 500Mbps 기가급 인터넷과 1인 집중 부스, 소회의실을 갖추고 있습니다. 일일권/월정액 이용 가능.",
    imageUrl: "https://placehold.co/1200x480/e2e8f0/94a3b8?text=강릉+코워킹스페이스",
  },
  {
    id: "3",
    name: "카페 보헤미안",
    category: "cafe",
    address: "강릉시 경강로 2021번길 30",
    lat: 37.7489,
    lng: 128.8772,
    wifi: { available: true, speedMbps: 50 },
    power: { level: "없음" },
    noise: "언급없음",
    openHours: "10:00 - 20:00",
    congestion: "high",
    tags: ["스페셜티", "분위기좋음"],
    description:
      "강릉 커피 문화의 원조. 고즈넉한 분위기와 훌륭한 커피를 즐길 수 있으나 콘센트가 없어 짧은 작업이나 미팅 용도에 적합합니다.",
    imageUrl: "https://placehold.co/1200x480/e2e8f0/94a3b8?text=카페+보헤미안",
  },
  {
    id: "4",
    name: "강릉시립도서관",
    category: "library",
    address: "강릉시 율곡로 3139번길 1",
    lat: 37.7512,
    lng: 128.8801,
    wifi: { available: true, speedMbps: 200 },
    power: { level: "충분함" },
    noise: "언급됨-조용함",
    openHours: "09:00 - 18:00",
    congestion: "low",
    tags: ["무료", "조용함", "집중"],
    description:
      "무료로 이용 가능한 시립 도서관. 열람실은 매우 조용하며 개인 좌석마다 콘센트가 구비되어 있습니다. 18시 이후 이용 불가.",
    imageUrl: "https://placehold.co/1200x480/e2e8f0/94a3b8?text=강릉시립도서관",
  },
  {
    id: "5",
    name: "씨마크 호텔 라운지",
    category: "hotel",
    address: "강릉시 해안로 558",
    lat: 37.8147,
    lng: 128.9215,
    wifi: { available: true, speedMbps: 300 },
    power: { level: "제한적" },
    noise: "언급됨-조용함",
    openHours: "07:00 - 22:00",
    congestion: "low",
    tags: ["오션뷰", "프리미엄", "조용함"],
    description:
      "동해 오션뷰를 바라보며 작업할 수 있는 프리미엄 호텔 라운지. 투숙객 외에도 음료 주문 시 이용 가능합니다.",
    imageUrl: "https://placehold.co/1200x480/e2e8f0/94a3b8?text=씨마크+호텔+라운지",
  },
  {
    id: "6",
    name: "버드나무 브루어리",
    category: "cafe",
    address: "강릉시 경강로 1961",
    lat: 37.7501,
    lng: 128.8765,
    wifi: { available: false },
    power: { level: "없음" },
    noise: "언급됨-시끄러움",
    openHours: "12:00 - 23:00",
    congestion: "high",
    tags: ["크래프트맥주", "야간작업불가"],
    description:
      "강릉 대표 크래프트 맥주 양조장 겸 펍. WiFi와 콘센트가 없어 업무용으로는 적합하지 않지만, 하루 마무리 네트워킹 장소로 추천합니다.",
    imageUrl: "https://placehold.co/1200x480/e2e8f0/94a3b8?text=버드나무+브루어리",
  },
];

export function getSpotById(id: string): WorkSpot | undefined {
  return MOCK_SPOTS.find((s) => s.id === id);
}
